// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd9XqaZeEnx9JW4aUsfsdXs5xbG5BxJYk',
    appId: '1:174970879477:web:591f5161ad1647b2af34bc',
    messagingSenderId: '174970879477',
    projectId: 'geet-ecommerce',
    authDomain: 'geet-ecommerce.firebaseapp.com',
    storageBucket: 'geet-ecommerce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj0E0JRF6YGoys9RmsyhSPVPGGQLBVT3E',
    appId: '1:174970879477:android:5886dc81c04331bcaf34bc',
    messagingSenderId: '174970879477',
    projectId: 'geet-ecommerce',
    storageBucket: 'geet-ecommerce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwcp7PHreUfGjNRgEhLfPHIJXJMV8fCw0',
    appId: '1:174970879477:ios:a4ad866ee96ba452af34bc',
    messagingSenderId: '174970879477',
    projectId: 'geet-ecommerce',
    storageBucket: 'geet-ecommerce.appspot.com',
    iosBundleId: 'com.example.geeta',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwcp7PHreUfGjNRgEhLfPHIJXJMV8fCw0',
    appId: '1:174970879477:ios:9690cdc3395e5c98af34bc',
    messagingSenderId: '174970879477',
    projectId: 'geet-ecommerce',
    storageBucket: 'geet-ecommerce.appspot.com',
    iosBundleId: 'com.example.geeta.RunnerTests',
  );
}
